### ISSUE TITLE
Functionality brainstorm

### ISSUE THREAD

**Issue by saekort** [saekort/PFS-Scenariotracker#2]
STORM!

**Comment by NieskeL** [comment]
Do we want a link to the reviews on the paizo site?

**Comment by NieskeL** [comment]
Ik denk dat verwijderde scenario's niet standaard weergegeven moeten worden. Want als je iets zoekt om binnen PFS te kunnen spelen, dan is het nutteloos om scenario's weer te geven die je toch niet kan spelen voor credit (blij maken met een dooie mus). 
Ik denk dat het handiger is om aan te vinken dat je de archived scenario's WEL wilt zien.

**Comment by saekort** [comment]
Retired lijkt me idd een optie om standaard uit te zetten, maar we moeten ze wel meenemen natuurlijk, de optie.
