### ISSUE TITLE
XP management

### ISSUE THREAD

**Issue by FlavienKnuchel** [saekort/PFS-Scenariotracker#36]
Could be interesting to add an optional "xp" information to the character, so we can use this to track the progression of each character inside a level (like level 2 + 1xp, or level 2.1).

**Comment by saekort** [comment]
Hmm yeah possibly. :)

Hows the translation bit going?

**Comment by FlavienKnuchel** [comment]
It's going good, that's my schedule and holidays that took me away from the project for some weeks, but back to routine from today :)

**Comment by saekort** [comment]
Sweet :)

**Comment by FlavienKnuchel** [comment]
Rebased my branch with the master, edited french translation, last step to go is language switch and localstorage.

Anyway, since the application is in https, it seems I can't use a local version anymore, my XMLhttpRequest being rejected. Any idea how I could have it back up again? I kinda need this to work on the menu and check my translations.

**Comment by saekort** [comment]
What do you mean your XHR is rejected? You just use a self signed certificate on your side?

**Comment by FlavienKnuchel** [comment]
Nevermind, I was opening it the wrong way ^_^

Thanks for the XP, that's perfect
