### ISSUE TITLE
Exporter not working with new Paizo website

### ISSUE THREAD

**Issue by Quairon-Nailo** [saekort/PFS-Scenariotracker#46]
In the new Paizo website, the Sessions tab on the profile leads to an error page. The new way to access your sessions is My Organized Play -> My sessions (which leads to https://secure.paizo.com/cgi-bin/WebObjects/Store.woa/wa/browse?path=organizedPlay/myAccount/playersessions#tabs ), and the plugin doesn't work there.

**Comment by saekort** [comment]
This is true. Though the session importing has never been released and is still only half functional. That said, the script is being maintained by someone else. Will close this for now, maybe in the future we will revisit importing from paizo.com.
