### ISSUE TITLE
PFS Tracker API (question)

### ISSUE THREAD

**Issue by Danscath** [saekort/PFS-Scenariotracker#52]
Hello there! Im working to implement one kinda of calendar for groups with some easy steps, like select one range of days, then each player select what day (morning, afternoon...)  and what mode (online, offline) and after that select a master and a game so I think that could be soooo nice if I could access to some data from pfstracker via API, to get what games are available for those players if they have account on pfstracker.

**Comment by saekort** [comment]
Wow I have no idea how I missed this for like a year.

Yeah so you can do something like that. You can call the 'scenarios' endpoint: `scenarios?rows=15&page=1&scenarios=true&modules=true&game_sfs=true&season_sfs[]=4&campaign=pfs&specials=true&orderBy=season&order=asc`

Check the code for documentation. It allows you to list the players as well and will return the info for you, no login neccessary.
