### ISSUE TITLE
Wat moet er in de Alfa?

### ISSUE THREAD

**Issue by NieskeL** [saekort/PFS-Scenariotracker#7]
Misschien handig om hier even te brainstormen over onze alfa-versie

- Wilden we zowel de speler-pagina als de scenariokiezer in de alfa hebben?
- Wilden we alle filteropties al werkend hebben, of gewoon een paar demonstratie-filters?

**Comment by saekort** [comment]
Alpha!

Ik zou zeggen we doen een aantal filters. Bv seasons, level range en wellicht authors.

Nog geen koppeling met personen?
